#!/bin/bash
if command -v clang-tidy &> /dev/null; then
  echo "Running clang-tidy..."
  # Example command, assumes compile_commands.json exists (generated by cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON)
  clang-tidy src/**/*.cpp -p build_tests
else
  echo "clang-tidy not found. Skipping static analysis."
fi
